catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('adaptations/', views.AdaptationListView.as_view(), name='adaptations'),
    path('adaptation/<int:pk>', views.AdaptationDetailView.as_view(), name='adaptation-detail'),
    path('directors/', views.DirectorListView.as_view(), name='directors'),
    path('director/<int:pk>', views.DirectorDetailView.as_view(), name='director-detail'),
]

library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
    # static(settings.STATIC_URL, document_root=settings.STATIC_ROOT),
]

catalog/models.py
from django.db import models
from django.urls import reverse 
from django.core.validators import MinValueValidator, MaxValueValidator
# from django_countries.fields import CountryField
import uuid

# Create your models here.
class Genre(models.Model):
    """Model representing a book genre."""
    name = models.CharField(max_length=200, help_text='Enter a book genre (e.g. Science Fiction)')
    
    def __str__(self):
        """String for representing the Model object."""
        return self.name

class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    year = models.PositiveIntegerField('Publishing year', null=True, validators=[MaxValueValidator(2020), MinValueValidator(1800)], help_text='Enter a publishing year')
    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField('ISBN', max_length=13, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')
    
    def __str__(self):
        """String for representing the Model object."""
        return self.title
    
    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('book-detail', args=[str(self.id)])

class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)
    nationality = models.CharField(max_length=100, null=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.last_name}, {self.first_name}'

class Director(models.Model):
    """Model representing a movie director."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)
    nationality = models.CharField(max_length=100, null=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """Returns the url to access a particular director instance."""
        return reverse('director-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.last_name}, {self.first_name}'



class Adaptation(models.Model):
    """Model representing a movie adaptation of the book."""
    title = models.CharField(max_length=200)
    director = models.ForeignKey('Director', on_delete=models.SET_NULL, null=True)
    original = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    year = models.PositiveIntegerField('Release year', null=True, validators=[MaxValueValidator(2020), MinValueValidator(1800)], help_text='Enter a publishing year')
    link = models.CharField('Link', max_length=255, help_text='Provide an IMDB link')
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this movie')
    
    def __str__(self):
        """String for representing the Model object."""
        return self.title
    
    def get_absolute_url(self):
        """Returns the url to access a detail record for this movie."""
        return reverse('adaptation-detail', args=[str(self.id)])

catalog/views.py
from django.shortcuts import render
from catalog.models import Author, Genre, Book, Director, Adaptation
from django.views import generic
from django.db.models import Q

# Create your views here.
def index(request):
    """View function for home page of site."""

    num_books = Book.objects.all().count()
    num_adaptations = Adaptation.objects.all().count()
    num_authors = Author.objects.count()
    num_directors = Director.objects.count()
    
    context = {
        'num_books': num_books,
        'num_adaptations': num_adaptations,
        'num_directors': num_directors,
        'num_authors': num_authors,
    }

    return render(request, 'index.html', context=context)

class BookListView(generic.ListView):
    queryset = Book.objects.order_by('year')
    model = Book

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['genre'] = Genre.objects.all() 
        context['author'] = Author.objects.all()
        return context
    
    def get_queryset(self):
        qs = super().get_queryset()
        filterName = self.request.GET.get('filterName')
        filterYear = self.request.GET.get('filterYear')
        filterGenre = self.request.GET.get('filterGenre')
        filterAuthor = self.request.GET.get('filterAuthor')
       
        if filterName != '' and filterName is not None:
            qs = qs.filter(title__icontains=filterName)
        if filterYear != '' and filterYear is not None and filterYear.isnumeric():
            qs = qs.filter(year__icontains=filterYear)
        if filterGenre != '' and filterGenre is not None and filterGenre != 'Choose genre...':
            qs = qs.filter(genre__name=filterGenre)
        if filterAuthor != '' and filterAuthor is not None and filterAuthor != 'Choose author...':
            filterAuthor.replace(" ", "")
            result = [x.strip() for x in filterAuthor.split(',')]
            print(result[1])
            print(result[0])
            qs = qs.filter(Q(author__first_name__icontains=result[1]) & Q(author__last_name__icontains=result[0]))

        return qs

class BookDetailView(generic.DetailView):
    model = Book

class AuthorListView(generic.ListView):
    model = Author
    queryset = Author.objects.order_by('date_of_birth')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        nat = Author.objects.values_list('nationality', flat=True).distinct().order_by()
        context['nationality'] = nat
        return context

    def get_queryset(self):
        qs = super().get_queryset()
        filterFirstName = self.request.GET.get('filterFirstName')
        filterLastName = self.request.GET.get('filterLastName')
        filterDate = self.request.GET.get('filterDate')
        filterNationality = self.request.GET.get('filterNationality')
        print('Yo, ', filterNationality)

        if filterFirstName != '' and filterFirstName is not None:
            qs = qs.filter(first_name__icontains=filterFirstName)
        if filterLastName != '' and filterLastName is not None:
            qs = qs.filter(last_name__icontains=filterLastName)
        if filterDate != '' and filterDate is not None:
            qs = qs.filter(date_of_birth__icontains=filterDate)
        if filterNationality != '' and filterNationality is not None and filterNationality != 'Choose nationality...':
            qs = qs.filter(nationality__icontains=filterNationality)

        return qs

class AuthorDetailView(generic.DetailView):
    model = Author

class AdaptationListView(generic.ListView):
    model = Adaptation
    queryset = Adaptation.objects.order_by('year')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['genre'] = Genre.objects.all() 
        context['director'] = Director.objects.all()
        return context

    def get_queryset(self):
        qs = super().get_queryset()
        filterName = self.request.GET.get('filterName')
        filterYear = self.request.GET.get('filterYear')
        filterGenre = self.request.GET.get('filterGenre')
        filterDirector = self.request.GET.get('filterDirector')
       
        if filterName != '' and filterName is not None:
            qs = qs.filter(title__icontains=filterName)
        if filterYear != '' and filterYear is not None and filterYear.isnumeric():
            qs = qs.filter(year__icontains=filterYear)
        if filterGenre != '' and filterGenre is not None and filterGenre != 'Choose genre...':
            qs = qs.filter(genre__name=filterGenre)
        if filterDirector != '' and filterDirector is not None and filterDirector != 'Choose director...':
            filterDirector.replace(" ", "")
            result = [x.strip() for x in filterDirector.split(',')]
            print(result[1])
            print(result[0])
            qs = qs.filter(Q(director__first_name__icontains=result[1]) & Q(director__last_name__icontains=result[0]))
        
        return qs

class AdaptationDetailView(generic.DetailView):
    model = Adaptation

class DirectorListView(generic.ListView):
    model = Director
    queryset = Director.objects.order_by('date_of_birth')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        nat = Director.objects.values_list('nationality', flat=True).distinct().order_by()
        context['nationality'] = nat
        return context

    def get_queryset(self):
        qs = super().get_queryset()
        filterFirstName = self.request.GET.get('filterFirstName')
        filterLastName = self.request.GET.get('filterLastName')
        filterDate = self.request.GET.get('filterDate')
        filterNationality = self.request.GET.get('filterNationality')
        print('Yo, ', filterFirstName)

        if filterFirstName != '' and filterFirstName is not None:
            qs = qs.filter(first_name__icontains=filterFirstName)
        
        if filterLastName != '' and filterLastName is not None:
            qs = qs.filter(last_name__icontains=filterLastName)
        
        if filterDate != '' and filterDate is not None:
            qs = qs.filter(date_of_birth__icontains=filterDate)

        if filterNationality != '' and filterNationality is not None and filterNationality != 'Choose nationality...':
            qs = qs.filter(nationality__icontains=filterNationality)

        return qs

class DirectorDetailView(generic.DetailView):
    model = Director

catalog/templates/catalog/adaptation_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ adaptation.title }}</h1>

  <p><strong>Director:</strong> <a href="{% url 'director-detail' adaptation.director.pk %}">{{ adaptation.director }}</a></p> 
  <p><strong>Original:</strong> <a href="{% url 'book-detail' adaptation.original.pk %}">{{ adaptation.original }}</a></p> 
  <p><strong>Release year:</strong> {{ adaptation.year }}</p> 
  <p><strong>Link:</strong> <a href="{{ adaptation.link }}">{{ adaptation.title }}</a></p> 
  <p><strong>Genre:</strong> {{ adaptation.genre.all|join:", " }}</p>  

  <!-- <div style="margin-left:20px;margin-top:20px">
    <h4>Adaptations</h4>
    {% if movie_list %}
      {% for movie in original.adaptation_set.all %}
        <p><strong>Adaptation:</strong> {{ movie.title }}</p>
        <p><strong>Release year:</strong> {{ movie.year }}</p>
      {% endfor %}
    {% else %}
      <p><strong>There are no movie adaptations of this book yet.</strong></p>
    {% endif %}
  </div> -->
{% endblock %}

catalog/templates/catalog/adaptation_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Adaptation List</h1>

  <h4>Filter by:</h4>

  <form method="GET" action=".">
  <div class="form-row">
    <div class="form-group col-md-2">
      <label for="filterYear">Release year</label>
      <input type="date" placeholder="yyyy" class="form-control" id="filterYear" name="filterYear" maxlength=4>
    </div>
    <div class="form-group col-md-4">
      <label for="filterName">Title</label>
      <input type="text" class="form-control" placeholder="Title contains..." id="filterName" name="filterName">
    </div>
    <div class="form-group col-md-2">
        <label for="filterGenre">Genre</label>
        <select id="filterGenre" class="form-control" name="filterGenre">
          <option selected>Choose genre...</option>
          {% for gen in genre %}
          <option value="{{ gen }}">{{ gen }}</option>
          {% endfor %}
        </select>
    </div>
    <div class="form-group col-md-2">
          <label for="filterDirector">Director</label>
          <select id="filterDirector" class="form-control" name="filterDirector">
          <option selected>Choose director...</option>
          {% for dir in director %}
          <option value="{{ dir }}">{{ dir }}</option>
          {% endfor %}
          </select>
    </div>
  </div>
  <input class="btn btn-primary" type="submit" value="Filter">
  <a class="btn btn-primary" href="{% url 'adaptations' %}" id="reset_button">Reset</a>
  </form>
  
  <hr />
  {% if adaptation_list %}
  <ul>
    {% for adaptation in adaptation_list %}
      <li>
        <a href="{{ adaptation.get_absolute_url }}">{{ adaptation.title }}</a> (dir. by {{adaptation.director.first_name}} {{adaptation.director.last_name}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no adaptations in the library.</p>
  {% endif %}       
{% endblock %}

catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>{{ author.last_name}}, {{ author.first_name }}</h1>

  <p><strong>Date of birth:</strong> {{ author.date_of_birth }}</p>
  {% if author.date_of_death %}
    <p><strong>Date of death:</strong> {{ author.date_of_death }}</p>
  {% endif %}
  <p><strong>Nationality:</strong> {{ author.nationality }}</p> 

  <div style="margin-left:20px;margin-top:20px">
    <h4>Books</h4>

    {% for book in author.book_set.all %}
      <hr>
      <p><strong><a href="{% url 'book-detail' book.pk %}">{{ book.title }}</a></strong> ({{ book.year }})</p>
      <!-- <p class="text-muted"><strong>Publication year:</strong> {{ book.year }}</p> -->
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Author List</h1>
  
  <h4>Filter by:</h4>

  <form method="GET" action=".">
  <div class="form-row">
    <div class="form-group col-md-2">
      <label for="filterDate">Date of birth</label>
      <input type="date" placeholder="yyyy-mm-dd" class="form-control" id="filterDate" name="filterDate">
    </div>
    <div class="form-group col-md-3">
      <label for="filterFirstName">First name</label>
      <input type="text" class="form-control" placeholder="First name contains..." id="filterFirstName" name="filterFirstName">
    </div>
    <div class="form-group col-md-3">
        <label for="filterLastName">Last name</label>
        <input type="text" class="form-control" placeholder="Last name contains..." id="filterLastName" name="filterLastName">
      </div>
    <div class="form-group col-md-2">
      <label for="filterNationality">Nationality</label>
      <select id="filterNationality" class="form-control" name="filterNationality">
        <option selected>Choose nationality...</option>
        {% for nat in nationality %}
        <option value="{{ nat }}">{{ nat }}</option>
        {% endfor %}
      </select>
    </div>
  </div>
  <input class="btn btn-primary" type="submit" value="Filter">
  <a class="btn btn-primary" href="{% url 'authors' %}" id="reset_button">Reset</a>

  </form>
  <hr />

  {% if author_list %}
  <ul>
    {% for author in author_list %}
      <li>
        <a href="{{ author.get_absolute_url }}">{{ author.last_name }}, {{ author.first_name }} ({{ author.date_of_birth }} - {{ author.date_of_death }})</a>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no authors in the database.</p>
  {% endif %}       
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a></p> 
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p> 
  <p><strong>Publication year:</strong> {{ book.year }}</p> 
  <p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>  

  <!-- <div style="margin-left:20px;margin-top:20px">
    <h4>Adaptations</h4>
    {% if movie_list %}
      {% for movie in original.adaptation_set.all %}
        <p><strong>Adaptation:</strong> {{ movie.title }}</p>
        <p><strong>Release year:</strong> {{ movie.year }}</p>
      {% endfor %}
    {% else %}
      <p><strong>There are no movie adaptations of this book yet.</strong></p>
    {% endif %}
  </div> -->

  <div style="margin-left:20px;margin-top:20px">
    <h4>Adaptations</h4>
    {% if book.adaptation_set.all %} 
      <!-- book.has_adaptation = True -->
      {% for adaptation in book.adaptation_set.all %}
        <hr>
        <p><strong><a href="{% url 'adaptation-detail' adaptation.pk %}">{{ adaptation.title }}</a></strong> ({{ adaptation.year }})</p>
        <!-- <p class="text-muted"><strong>Publication year:</strong> {{ book.year }}</p> -->
     {% endfor %}
    {% else %}
      <p class="text-muted">There are no adaptations of this book yet.</p>
    {% endif %}
  </div>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Book List</h1>
  <h4>Filter by:</h4>

  <form method="GET" action=".">
    <div class="form-row">
      <div class="form-group col-md-2">
        <label for="filterYear">Publication year</label>
        <input type="date" placeholder="yyyy" class="form-control" id="filterYear" name="filterYear" maxlength=4>
      </div>
      <div class="form-group col-md-4">
        <label for="filterName">Title</label>
        <input type="search" class="form-control" placeholder="Title contains..." id="filterName" name="filterName">
      </div>
      <div class="form-group col-md-2">
        <label for="filterGenre">Genre</label>
        <select id="filterGenre" class="form-control" name="filterGenre">
          <option selected>Choose genre...</option>
          {% for gen in genre %}
          <option value="{{ gen }}">{{ gen }}</option>
          {% endfor %}
        </select>
      </div>
      <div class="form-group col-md-2">
          <label for="filterAuthor">Author</label>
          <select id="filterAuthor" class="form-control" name="filterAuthor">
          <option selected>Choose author...</option>
          {% for aut in author %}
          <option value="{{ aut }}">{{ aut }}</option>
          {% endfor %}
          </select>
      </div>
    </div>
    <!-- <button type="submit" class="btn btn-primary">Filter</button> -->
    <input class="btn btn-primary" type="submit" value="Filter">
    <a class="btn btn-primary" href="{% url 'books' %}" id="reset_button">Reset</a>
  </form>

  <hr />
  {% if book_list %}
  <ul>
    {% for book in book_list %} 
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no books in the library.</p>
  {% endif %}       
{% endblock %}

catalog/templates/catalog/director_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>{{ director.last_name}}, {{ director.first_name }}</h1>

  <p><strong>Date of birth:</strong> {{ director.date_of_birth }}</p>
  {% if director.date_of_death %}
    <p><strong>Date of death:</strong> {{ director.date_of_death }}</p>
  {% endif %}
  <p><strong>Nationality:</strong> {{ director.nationality }}</p> 

  <div style="margin-left:20px;margin-top:20px">
    <h4>Adaptations</h4>

    {% for adaptation in director.adaptation_set.all %}
      <hr>
      <p><strong><a href="{% url 'adaptation-detail' adaptation.pk %}">{{ adaptation.title }}</a></strong> ({{ adaptation.year }})</p>
      <!-- <p class="text-muted"><strong>Publication year:</strong> {{ book.year }}</p> -->
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/director_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Director List</h1>
  
  <h4>Filter by:</h4>

  <form method="GET" action=".">
    <div class="form-row">
      <div class="form-group col-md-2">
        <label for="filterDate">Date of birth</label>
        <input type="date" placeholder="yyyy-mm-dd" class="form-control" id="filterDate" name="filterDate">
      </div>
      <div class="form-group col-md-3">
        <label for="filterFirstName">First name</label>
        <input type="text" class="form-control" placeholder="First name contains..." id="filterFirstName" name="filterFirstName">
      </div>
      <div class="form-group col-md-3">
          <label for="filterLastName">Last name</label>
          <input type="text" class="form-control" placeholder="Last name contains..." id="filterLastName" name="filterLastName">
        </div>
      <div class="form-group col-md-2">
        <label for="filterNationality">Nationality</label>
        <select id="filterNationality" class="form-control" name="filterNationality">
          <option selected>Choose nationality...</option>
          {% for nat in nationality %}
          <option value="{{ nat }}">{{ nat }}</option>
          {% endfor %}
        </select>
      </div>
    </div>
    <input class="btn btn-primary" type="submit" value="Filter">
    <a class="btn btn-primary" href="{% url 'directors' %}" id="reset_button">Reset</a>
    </form>

  <hr />
  {% if director_list %}
  <ul>
    {% for director in director_list %}
      <li>
        <a href="{{ director.get_absolute_url }}">{{ director.last_name }}, {{ director.first_name }} ({{ director.date_of_birth }} - {{ director.date_of_death }})</a>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no directors in the database.</p>
  {% endif %}       
{% endblock %}